export const maxDuration = 60;

export default async function handler(req, res) {
  // Only POST requests
  if (req.method !== "POST") {
    return res.status(405).json({
      success: false,
      error: "Only POST requests are allowed"
    });
  }

  try {
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
      return res.status(500).json({
        success: false,
        error: "GEMINI_API_KEY is not configured in Vercel Environment Variables."
      });
    }

    const body = req.body || {};

    const idea = String(body.idea || "").trim();

    // User can send 10 or 20.
    // Default = 10
    const requestedEpisodeCount = Number(body.episodeCount || 10);

    const episodeCount =
      requestedEpisodeCount === 20 ? 20 : 10;

    const language =
      String(body.language || "Hinglish").trim();

    const genre =
      String(body.genre || "Cinematic Story").trim();

    const duration =
      Number(body.duration || 60);

    if (!idea) {
      return res.status(400).json({
        success: false,
        error: "Idea is required."
      });
    }

    // ---------------------------------------------------------
    // GEMINI PROMPT
    // ---------------------------------------------------------

    const prompt = `
You are the main story writer and showrunner for an AI short-video platform called ViralTap.

USER STORY IDEA:
${idea}

STORY SETTINGS:
- Genre: ${genre}
- Language: ${language}
- Number of episodes: EXACTLY ${episodeCount}
- Target video duration per episode: approximately ${duration} seconds

IMPORTANT:
Do NOT create a tiny 20-second demo story.

Create a COMPLETE CONNECTED SEASON.

The season must feel like a real web-series / short-video series where every episode continues the same story.

CORE REQUIREMENTS:

1. Create exactly ${episodeCount} episodes.
2. Every episode must connect to the previous episode.
3. Maintain character continuity throughout the entire season.
4. Remember important events, relationships, secrets and conflicts.
5. Do not randomly change character personalities or names.
6. Each episode must have a proper beginning, development and ending.
7. Each episode must contain a strong hook in the first few seconds.
8. Each episode must contain meaningful story progression.
9. Each episode must end with a strong cliffhanger, mystery, reveal or reason to watch the next episode.
10. Do NOT finish the entire story in Episode 1.
11. Do NOT repeat the same information in every episode.
12. Build tension progressively.
13. Include twists, but make them logically connected to earlier events.
14. The finale must resolve the main season conflict while leaving an optional hook for Season 2.
15. Write natural spoken narration/dialogue suitable for an AI voice.
16. Avoid robotic, generic phrases such as:
   "Aaj ki kahani..."
   "Aur phir ek twist aata hai..."
   unless they genuinely fit the story.
17. The writing should feel like a professional Indian short-series / OTT-style story.
18. Use simple, natural ${language}.
19. Do not write production instructions inside narration.
20. Do not mention that the story was generated by AI.

EPISODE LENGTH:

Each episode should have a substantial script.

For approximately ${duration} seconds, write enough spoken content for a proper short video.

Do NOT make an episode only 2-3 sentences.

Each episode should normally contain:
- 8 to 12 scenes
- meaningful narration/dialogue
- visual description for every scene
- strong opening hook
- strong ending cliffhanger

CHARACTER CONTINUITY:

First create the main characters.

For each character provide:
- name
- age
- role
- personality
- appearance
- relationship to other important characters

VISUAL CONTINUITY:

Every visual prompt must describe characters consistently.

When a character appears again, keep:
- same approximate age
- same hairstyle
- same clothing style
- same physical appearance
- same personality
- same environment where appropriate

Each visual prompt should be detailed enough for an image-generation model.

Avoid generic visual prompts like:
"cinematic scene related to the story"

Instead describe exactly what is visible.

For example:
"19-year-old Indian boy with messy black hair, wearing a dark blue shirt, standing alone on a rainy railway platform at night, worried expression, cinematic lighting, realistic Indian environment, close-up shot"

SCENE STRUCTURE:

Each scene should contain:
- scene number
- approximate duration
- narration
- dialogue if needed
- visual prompt
- camera shot
- mood

The narration should be ready to send directly to a voice-generation system.

SEASON STRUCTURE:

The season should have:
- season title
- logline
- overall story
- characters
- episodes
- season finale
- possible Season 2 hook

STORY PACING:

Episodes 1-2:
Introduce world, characters and central problem.

Episodes 3-5:
Increase conflict and reveal important information.

Episodes 6-8:
Major twists, danger and emotional escalation.

Episodes 9-${episodeCount - 1}:
Major confrontation and final revelations.

Episode ${episodeCount}:
Season finale.
Resolve the main conflict but leave a logical optional hook for another season.

MOST IMPORTANT:

Return ONLY valid JSON.

Do not use markdown.
Do not use \`\`\`json.
Do not add explanations before or after the JSON.
`;

    // ---------------------------------------------------------
    // JSON SCHEMA
    // ---------------------------------------------------------

    const sceneSchema = {
      type: "OBJECT",
      properties: {
        scene: {
          type: "INTEGER"
        },
        duration: {
          type: "INTEGER"
        },
        narration: {
          type: "STRING"
        },
        dialogue: {
          type: "STRING"
        },
        visualPrompt: {
          type: "STRING"
        },
        cameraShot: {
          type: "STRING"
        },
        mood: {
          type: "STRING"
        }
      },
      required: [
        "scene",
        "duration",
        "narration",
        "dialogue",
        "visualPrompt",
        "cameraShot",
        "mood"
      ]
    };

    const characterSchema = {
      type: "OBJECT",
      properties: {
        name: {
          type: "STRING"
        },
        age: {
          type: "INTEGER"
        },
        role: {
          type: "STRING"
        },
        personality: {
          type: "STRING"
        },
        appearance: {
          type: "STRING"
        },
        relationship: {
          type: "STRING"
        }
      },
      required: [
        "name",
        "age",
        "role",
        "personality",
        "appearance",
        "relationship"
      ]
    };

    const episodeSchema = {
      type: "OBJECT",
      properties: {
        episode: {
          type: "INTEGER"
        },
        title: {
          type: "STRING"
        },
        summary: {
          type: "STRING"
        },
        hook: {
          type: "STRING"
        },
        script: {
          type: "STRING"
        },
        cliffhanger: {
          type: "STRING"
        },
        scenes: {
          type: "ARRAY",
          items: sceneSchema
        }
      },
      required: [
        "episode",
        "title",
        "summary",
        "hook",
        "script",
        "cliffhanger",
        "scenes"
      ]
    };

    const responseSchema = {
      type: "OBJECT",
      properties: {
        seasonTitle: {
          type: "STRING"
        },
        logline: {
          type: "STRING"
        },
        overallStory: {
          type: "STRING"
        },
        characters: {
          type: "ARRAY",
          items: characterSchema
        },
        episodes: {
          type: "ARRAY",
          minItems: episodeCount,
          maxItems: episodeCount,
          items: episodeSchema
        },
        seasonFinale: {
          type: "STRING"
        },
        season2Hook: {
          type: "STRING"
        }
      },
      required: [
        "seasonTitle",
        "logline",
        "overallStory",
        "characters",
        "episodes",
        "seasonFinale",
        "season2Hook"
      ]
    };

    // ---------------------------------------------------------
    // GEMINI API REQUEST
    // ---------------------------------------------------------

    const geminiResponse = await fetch(
      "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-goog-api-key": apiKey
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                {
                  text: prompt
                }
              ]
            }
          ],

          generationConfig: {
            temperature: 0.9,
            topP: 0.95,
            maxOutputTokens: 50000,

            responseMimeType: "application/json",

            responseSchema
          }
        })
      }
    );

    // ---------------------------------------------------------
    // HANDLE GEMINI ERROR
    // ---------------------------------------------------------

    if (!geminiResponse.ok) {
      const errorText = await geminiResponse.text();

      console.error("Gemini API Error:", errorText);

      return res.status(geminiResponse.status).json({
        success: false,
        error: "Gemini API request failed.",
        details: errorText
      });
    }

    const geminiData = await geminiResponse.json();

    // ---------------------------------------------------------
    // GET GENERATED TEXT
    // ---------------------------------------------------------

    const generatedText =
      geminiData?.candidates?.[0]?.content?.parts
        ?.map((part) => part.text || "")
        .join("")
        .trim();

    if (!generatedText) {
      console.error(
        "Empty Gemini response:",
        JSON.stringify(geminiData)
      );

      return res.status(500).json({
        success: false,
        error: "Gemini returned an empty response."
      });
    }

    // ---------------------------------------------------------
    // PARSE JSON
    // ---------------------------------------------------------

    let season;

    try {
      season = JSON.parse(generatedText);
    } catch (parseError) {
      console.error(
        "JSON Parse Error:",
        parseError,
        generatedText
      );

      return res.status(500).json({
        success: false,
        error: "Gemini returned invalid JSON."
      });
    }

    // ---------------------------------------------------------
    // BASIC VALIDATION
    // ---------------------------------------------------------

    if (
      !season ||
      !Array.isArray(season.episodes) ||
      season.episodes.length !== episodeCount
    ) {
      return res.status(500).json({
        success: false,
        error: `Expected exactly ${episodeCount} episodes but received an invalid season.`
      });
    }

    // Make sure episode numbers are correct
    season.episodes = season.episodes.map(
      (episode, index) => ({
        ...episode,
        episode: index + 1
      })
    );

    // ---------------------------------------------------------
    // BACKWARD COMPATIBILITY
    //
    // Existing frontend expects "scenes".
    // We expose Episode 1 scenes here so the current UI
    // doesn't completely break while we upgrade the frontend.
    // ---------------------------------------------------------

    const firstEpisode = season.episodes[0];

    return res.status(200).json({
      success: true,

      // New season data
      seasonTitle: season.seasonTitle,
      logline: season.logline,
      overallStory: season.overallStory,
      characters: season.characters,
      episodes: season.episodes,
      seasonFinale: season.seasonFinale,
      season2Hook: season.season2Hook,

      // Existing frontend compatibility
      title: season.seasonTitle,

      totalEpisodes: episodeCount,

      totalDuration:
        season.episodes.reduce((total, episode) => {
          return (
            total +
            (Array.isArray(episode.scenes)
              ? episode.scenes.reduce(
                  (sceneTotal, scene) =>
                    sceneTotal + Number(scene.duration || 0),
                  0
                )
              : 0)
          );
        }, 0),

      scenes: firstEpisode?.scenes || [],

      firstEpisode: firstEpisode || null
    });

  } catch (error) {
    console.error("Server Error:", error);

    return res.status(500).json({
      success: false,
      error: "Server error while generating the season.",
      details: error?.message || "Unknown error"
    });
  }
}
